# Generated by Django 5.2.4 on 2025-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Grains & Cereals', 'Grains & Cereals'), ('Legumes & Pulses', 'Legumes & Pulses'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Nuts & Seeds', 'Nuts & Seeds'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Dairy', 'Dairy'), ('Oils', 'Oils'), ('Spices', 'Spices'), ('Sweeteners', 'Sweeteners'), ('Others', 'Others')], max_length=30)),
                ('product_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan')], default='Veg', max_length=10)),
            ],
        ),
    ]
