"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "hi" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  hi: {
    // Navigation
    "nav.dashboard": "डैशबोर्ड",
    "nav.suppliers": "आपूर्तिकर्ता",
    "nav.orders": "ऑर्डर",
    "nav.bulk_orders": "बल्क ऑर्डर",
    "nav.inventory": "इन्वेंटरी",
    "nav.tracking": "ट्रैकिंग",
    "nav.payments": "भुगतान",
    "nav.admin": "एडमिन",
    "nav.help": "सहायता",
    "nav.login": "लॉगिन",
    "nav.logout": "लॉगआउट",

    // Landing Page
    "landing.title": "भारत के स्ट्रीट फूड वेंडर्स को",
    "landing.subtitle": "सशक्त बनाएं",
    "landing.description": "विश्वसनीय आपूर्तिकर्ताओं से जुड़ें, बेहतर दाम पाएं, और अपना व्यापार बढ़ाएं। हजारों वेंडर्स का भरोसा।",
    "landing.get_started": "शुरू करें",
    "landing.watch_demo": "डेमो देखें",
    "landing.problems_solutions": "समस्याएं और समाधान",
    "landing.current_challenges": "वर्तमान चुनौतियां",
    "landing.with_vendorconnect": "VendorConnect के साथ",
    "landing.key_features": "मुख्य विशेषताएं",
    "landing.verified_suppliers": "सत्यापित आपूर्तिकर्ता",
    "landing.better_prices": "बेहतर दाम",
    "landing.local_network": "स्थानीय नेटवर्क",
    "landing.how_it_works": "यह कैसे काम करता है",
    "landing.register": "पंजीकरण करें",
    "landing.find_suppliers": "आपूर्तिकर्ता खोजें",
    "landing.place_order": "ऑर्डर करें",
    "landing.success_stories": "सफलता की कहानियां",
    "landing.start_today": "आज ही शुरू करें",
    "landing.start_free": "मुफ्त में शुरू करें",

    // Problem statements
    "landing.problem1": "अविश्वसनीय आपूर्तिकर्ता और गुणवत्ता की समस्या",
    "landing.problem2": "ऊंची लागत और छुपे हुए शुल्क",
    "landing.problem3": "थोक दरों तक पहुंच नहीं",
    "landing.problem4": "पारदर्शी मूल्य निर्धारण का अभाव",

    // Solutions
    "landing.solution1": "सत्यापित और विश्वसनीय आपूर्तिकर्ता",
    "landing.solution2": "पारदर्शी मूल्य निर्धारण",
    "landing.solution3": "सामूहिक खरीदारी से बेहतर दाम",
    "landing.solution4": "स्थानीय आपूर्तिकर्ताओं से तुरंत जुड़ाव",

    // Feature descriptions
    "landing.verified_desc": "सभी आपूर्तिकर्ता पूर्ण सत्यापन प्रक्रिया से गुजरते हैं। गुणवत्ता की गारंटी के साथ।",
    "landing.better_prices_desc": "सामूहिक खरीदारी और प्रतिस्पर्धी मूल्य निर्धारण से 15-30% तक की बचत।",
    "landing.local_network_desc": "आपके क्षेत्र के स्थानीय आपूर्तिकर्ताओं से जुड़ें। तेज़ डिलीवरी और कम लागत।",

    // How it works steps
    "landing.step1_desc": "अपना खाता बनाएं और अपनी आवश्यकताओं को बताएं",
    "landing.step2_desc": "अपने क्षेत्र के सत्यापित आपूर्तिकर्ताओं को ब्राउज़ करें",
    "landing.step3_desc": "बेहतर दामों पर ऑर्डर करें और तेज़ डिलीवरी पाएं",

    // Success stories
    "landing.vendor1_name": "राजेश कुमार",
    "landing.vendor1_role": "चाट वेंडर, दिल्ली",
    "landing.vendor1_quote":
      "VendorConnect से मेरी लागत 25% कम हो गई है। अब मुझे गुणवत्तापूर्ण सामग्री मिलती है और मेरे ग्राहक भी खुश हैं।",
    "landing.vendor2_name": "प्रिया शर्मा",
    "landing.vendor2_role": "दोसा स्टॉल, बैंगलोर",
    "landing.vendor2_quote": "पहले मुझे अलग-अलग जगह जाना पड़ता था। अब एक ही प्लेटफॉर्म से सब कुछ मिल जाता है।",

    // CTA section
    "landing.cta_desc": "हजारों वेंडर्स पहले से ही VendorConnect का उपयोग कर रहे हैं। आप भी जुड़ें!",

    // Footer
    "footer.tagline": "भारत के स्ट्रीट फूड वेंडर्स को सशक्त बनाना",
    "footer.help_center": "हेल्प सेंटर",
    "footer.contact": "संपर्क करें",
    "footer.faq": "FAQ",
    "footer.about": "हमारे बारे में",
    "footer.careers": "करियर",
    "footer.privacy": "प्राइवेसी पॉलिसी",
    "footer.rights": "सभी अधिकार सुरक्षित।",
    "footer.company": "कंपनी",

    // Login Page
    "login.welcome": "स्वागत है! 👋",
    "login.description": "अपने व्यापार को आगे बढ़ाने के लिए लॉग इन करें",
    "login.account_description": "अपने खाते में लॉग इन करें",
    "login.phone_number": "फोन नंबर",
    "login.email": "ईमेल पता",
    "login.password": "पासवर्ड",
    "login.password_placeholder": "अपना पासवर्ड डालें",
    "login.phone_placeholder": "9876543210",
    "login.email_placeholder": "your@email.com",
    "login.remember_me": "मुझे याद रखें",
    "login.forgot_password": "पासवर्ड भूल गए?",
    "login.login_button": "लॉग इन करें",
    "login.login_with_otp": "OTP से लॉग इन करें",
    "login.login_with_google": "Google से लॉग इन करें",
    "login.or": "या",
    "login.no_account": "खाता नहीं है?",
    "login.register": "रजिस्टर करें",
    "login.phone_tab": "फोन नंबर",
    "login.email_tab": "ईमेल",

    // Dashboard
    "dashboard.welcome": "नमस्ते राजेश जी! 👋",
    "dashboard.welcome_desc": "आपके व्यापार की स्थिति देखें और नए ऑर्डर करें",
    "dashboard.monthly_savings": "इस महीने की बचत",
    "dashboard.total_orders": "कुल ऑर्डर्स",
    "dashboard.active_suppliers": "एक्टिव सप्लायर्स",
    "dashboard.average_rating": "औसत रेटिंग",
    "dashboard.low_stock_alert": "कम स्टॉक अलर्ट",
    "dashboard.recent_orders": "हाल के ऑर्डर्स",
    "dashboard.top_suppliers": "टॉप आपूर्तिकर्ता",
    "dashboard.quick_actions": "त्वरित कार्य",
    "dashboard.find_suppliers": "नए सप्लायर खोजें",
    "dashboard.bulk_order": "बल्क ऑर्डर करें",
    "dashboard.market_prices": "मार्केट प्राइस देखें",
    "dashboard.price_alerts": "प्राइस अलर्ट सेट करें",
    "dashboard.manage_inventory": "इन्वेंटरी मैनेज करें",

    // Suppliers Page
    "suppliers.title": "आपूर्तिकर्ता",
    "suppliers.description": "सत्यापित और विश्वसनीय सप्लायर्स खोजें",
    "suppliers.search_placeholder": "सप्लायर या प्रोडक्ट खोजें...",
    "suppliers.select_category": "श्रेणी चुनें",
    "suppliers.select_location": "स्थान चुनें",
    "suppliers.all_categories": "सभी श्रेणियां",
    "suppliers.all_locations": "सभी स्थान",
    "suppliers.more_filters": "अधिक फिल्टर",
    "suppliers.results_found": "आपूर्तिकर्ता मिले",
    "suppliers.sort_by_rating": "रेटिंग के अनुसार",
    "suppliers.sort_by_distance": "दूरी के अनुसार",
    "suppliers.sort_by_price": "कीमत के अनुसार",
    "suppliers.sort_by_delivery": "डिलीवरी टाइम के अनुसार",
    "suppliers.min_order": "मिन ऑर्डर:",
    "suppliers.specialties": "विशेषताएं:",
    "suppliers.order_now": "ऑर्डर करें",
    "suppliers.view_details": "विवरण देखें",
    "suppliers.load_more": "और आपूर्तिकर्ता लोड करें",
    "suppliers.no_results": "कोई आपूर्तिकर्ता नहीं मिला",
    "suppliers.no_results_desc": "अपने खोज मापदंड बदलकर फिर से कोशिश करें",
    "suppliers.clear_filters": "फिल्टर साफ़ करें",

    // Orders Page
    "orders.title": "मेरे ऑर्डर्स",
    "orders.description": "अपने सभी ऑर्डर्स की जानकारी देखें",
    "orders.download_report": "रिपोर्ट डाउनलोड करें",
    "orders.search_placeholder": "ऑर्डर ID या सप्लायर खोजें...",
    "orders.status_filter": "स्टेटस फिल्टर",
    "orders.time_filter": "समय फिल्टर",
    "orders.all_status": "सभी स्टेटस",
    "orders.all_time": "सभी समय",
    "orders.today": "आज",
    "orders.this_week": "इस सप्ताह",
    "orders.this_month": "इस महीने",
    "orders.this_quarter": "इस तिमाही",
    "orders.order_history": "ऑर्डर हिस्ट्री",
    "orders.order_id": "ऑर्डर ID",
    "orders.supplier": "आपूर्तिकर्ता",
    "orders.items": "आइटम्स",
    "orders.amount": "राशि",
    "orders.status": "स्टेटस",
    "orders.order_date": "ऑर्डर डेट",
    "orders.action": "एक्शन",
    "orders.more_items": "और आइटम्स",
    "orders.pending_orders": "पेंडिंग ऑर्डर्स",
    "orders.processing_transit": "प्रोसेसिंग + ट्रांजिट",
    "orders.total_spent": "कुल खर्च",
    "orders.average_order": "औसत ऑर्डर",
    "orders.per_order": "प्रति ऑर्डर",
    "orders.orders_found": "ऑर्डर्स मिले",
    "orders.no_orders_found": "कोई ऑर्डर नहीं मिला",
    "orders.try_changing_filters": "अपने फिल्टर बदलकर फिर से कोशिश करें",

    // Bulk Orders
    "bulk.title": "बल्क ऑर्डर्स",
    "bulk.description": "अन्य वेंडर्स के साथ मिलकर बेहतर दाम पाएं",
    "bulk.create_new": "नया बल्क ऑर्डर बनाएं",
    "bulk.how_it_works": "बल्क ऑर्डर कैसे काम करता है?",
    "bulk.step1": "ऑर्डर बनाएं या जुड़ें",
    "bulk.step1_desc": "नया बल्क ऑर्डर बनाएं या मौजूदा ऑर्डर में शामिल हों",
    "bulk.step2": "टारगेट पूरा करें",
    "bulk.step2_desc": "जब टारगेट मात्रा पूरी हो जाए, ऑर्डर कन्फर्म हो जाता है",
    "bulk.step3": "बचत पाएं",
    "bulk.step3_desc": "बल्क रेट पर सामान मिलता है और सभी को फायदा होता है",
    "bulk.active_orders": "एक्टिव बल्क ऑर्डर्स",
    "bulk.completed_orders": "पूरे हो चुके ऑर्डर्स",
    "bulk.progress": "प्रगति:",
    "bulk.savings": "बचत",
    "bulk.bulk_price": "बल्क प्राइस",
    "bulk.market_price": "मार्केट प्राइस",
    "bulk.members": "सदस्य",
    "bulk.deadline": "बाकी",
    "bulk.join_order": "इस ऑर्डर में शामिल हों",
    "bulk.create_first": "पहला बल्क ऑर्डर बनाएं",
    // Bulk Orders - Additional keys
    "bulk_orders.subtitle": "अन्य वेंडर्स के साथ मिलकर बेहतर दाम पाएं",
    "bulk_orders.create_new": "नया बल्क ऑर्डर बनाएं",
    "bulk_orders.create_description": "अन्य वेंडर्स के साथ मिलकर बल्क में ऑर्डर करें और पैसे बचाएं",
    "bulk_orders.product_name": "प्रोडक्ट का नाम",
    "bulk_orders.product_placeholder": "जैसे: प्याज, चावल, मसाले",
    "bulk_orders.category": "श्रेणी",
    "bulk_orders.select_category": "श्रेणी चुनें",
    "bulk_orders.target_quantity": "टारगेट मात्रा",
    "bulk_orders.quantity_placeholder": "जैसे: 500 किलो",
    "bulk_orders.deadline": "डेडलाइन",
    "bulk_orders.description": "विवरण",
    "bulk_orders.description_placeholder": "प्रोडक्ट की गुणवत्ता और अन्य जरूरी जानकारी",
    "bulk_orders.create_order": "बल्क ऑर्डर बनाएं",
    "bulk_orders.how_it_works": "बल्क ऑर्डर कैसे काम करता है?",
    "bulk_orders.step1_title": "ऑर्डर बनाएं या जुड़ें",
    "bulk_orders.step1_desc": "नया बल्क ऑर्डर बनाएं या मौजूदा ऑर्डर में शामिल हों",
    "bulk_orders.step2_title": "टारगेट पूरा करें",
    "bulk_orders.step2_desc": "जब टारगेट मात्रा पूरी हो जाए, ऑर्डर कन्फर्म हो जाता है",
    "bulk_orders.step3_title": "बचत पाएं",
    "bulk_orders.step3_desc": "बल्क रेट पर सामान मिलता है और सभी को फायदा होता है",
    "bulk_orders.active_orders": "एक्टिव बल्क ऑर्डर्स",
    "bulk_orders.progress": "प्रगति",
    "bulk_orders.savings": "बचत",
    "bulk_orders.bulk_price": "बल्क प्राइस",
    "bulk_orders.market_price": "मार्केट प्राइस",
    "bulk_orders.members": "सदस्य",
    "bulk_orders.join_order": "इस ऑर्डर में शामिल हों",
    "bulk_orders.view_details": "विवरण देखें",
    "bulk_orders.completed_orders": "पूरे हो चुके ऑर्डर्स",
    "bulk_orders.no_active_orders": "कोई एक्टिव बल्क ऑर्डर नहीं",
    "bulk_orders.empty_state_desc": "नया बल्क ऑर्डर बनाएं या मौजूदा ऑर्डर में शामिल हों",
    "bulk_orders.create_first_order": "पहला बल्क ऑर्डर बनाएं",

    // Inventory
    "inventory.title": "इन्वेंटरी मैनेजमेंट",
    "inventory.description": "अपने स्टॉक को ट्रैक और मैनेज करें",
    "inventory.add_item": "नया आइटम जोड़ें",
    "inventory.total_items": "कुल आइटम्स",
    "inventory.low_stock": "कम स्टॉक अलर्ट",
    "inventory.stock_value": "कुल स्टॉक वैल्यू",
    "inventory.turnover": "औसत टर्नओवर",
    "inventory.in_stock": "स्टॉक में",
    "inventory.out_of_stock": "स्टॉक खत्म",
    "inventory.reorder_now": "तुरंत ऑर्डर करें",
    "inventory.search_placeholder": "आइटम खोजें...",
    "inventory.category_filter": "श्रेणी फिल्टर",
    "inventory.status_filter": "स्टेटस फिल्टर",
    "inventory.item": "आइटम",
    "inventory.category": "श्रेणी",
    "inventory.current_stock": "मौजूदा स्टॉक",
    "inventory.stock_level": "स्टॉक लेवल",
    "inventory.cost": "लागत",
    "inventory.avg_consumption": "औसत खपत",

    // Payments
    "payments.title": "पेमेंट्स",
    "payments.description": "सुरक्षित और आसान भुगतान विकल्प",
    "payments.choose_method": "भुगतान विधि चुनें",
    "payments.upi": "UPI",
    "payments.wallet": "डिजिटल वॉलेट",
    "payments.card": "डेबिट/क्रेडिट कार्ड",
    "payments.cod": "कैश ऑन डिलीवरी",
    "payments.order_summary": "ऑर्डर समरी",
    "payments.subtotal": "सब्टोटल",
    "payments.delivery_charge": "डिलीवरी चार्ज",
    "payments.processing_fee": "प्रोसेसिंग फीस",
    "payments.total_amount": "कुल राशि",
    "payments.pay_now": "का भुगतान करें",
    "payments.secure_payment": "🔒 आपका भुगतान 256-bit SSL एन्क्रिप्शन से सुरक्षित है",
    "payments.recent_transactions": "हाल के ट्रांजैक्शन",
    "payments.free": "मुफ्त",
    "payments.popular": "लोकप्रिय",

    // Tracking
    "tracking.title": "ऑर्डर ट्रैकिंग",
    "tracking.description": "अपने ऑर्डर की लाइव स्थिति देखें",
    "tracking.live_location": "लाइव लोकेशन",
    "tracking.order_status": "ऑर्डर स्टेटस",
    "tracking.estimated_delivery": "अपेक्षित डिलीवरी",
    "tracking.contact_info": "संपर्क जानकारी",
    "tracking.supplier": "आपूर्तिकर्ता",
    "tracking.delivery_partner": "डिलीवरी पार्टनर",
    "tracking.need_help": "सहायता चाहिए?",
    "tracking.chat_support": "चैट सपोर्ट",
    "tracking.helpline": "हेल्पलाइन: 1800-123-4567",
    "tracking.track_order": "ट्रैक करें",
    "tracking.tracking_id_placeholder": "ट्रैकिंग ID डालें (जैसे: TRK001235)",
    "tracking.distance_remaining": "बची दूरी",
    "tracking.expected_time": "अपेक्षित समय",
    "tracking.call_delivery": "डिलीवरी पार्टनर को कॉल करें",
    "tracking.message": "मैसेज करें",
    "tracking.order_progress": "ऑर्डर प्रगति",
    "tracking.order_confirmed": "ऑर्डर कन्फर्म",
    "tracking.packing": "पैकिंग",
    "tracking.in_transit": "ट्रांजिट में",
    "tracking.delivered": "डिलीवर हो गया",
    "tracking.delivery_address": "डिलीवरी पता",
    "tracking.order_summary": "ऑर्डर विवरण",
    "tracking.tracking_id": "ट्रैकिंग ID",

    // Common
    "common.search": "खोजें...",
    "common.filter": "फिल्टर",
    "common.save": "सेव करें",
    "common.cancel": "रद्द करें",
    "common.submit": "जमा करें",
    "common.edit": "एडिट करें",
    "common.delete": "डिलीट करें",
    "common.view_all": "सभी देखें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफल",
    "common.pending": "पेंडिंग",
    "common.completed": "पूर्ण",
    "common.active": "सक्रिय",
    "common.inactive": "निष्क्रिय",
    "common.next": "अगला",
    "common.previous": "पिछला",
    "common.close": "बंद करें",
    "common.open": "खोलें",
    "common.yes": "हाँ",
    "common.no": "नहीं",

    // Status
    "status.delivered": "डिलीवर हो गया",
    "status.in_transit": "ट्रांजिट में",
    "status.processing": "प्रोसेसिंग",
    "status.cancelled": "रद्द",
    "status.confirmed": "कन्फर्म",
    "status.packed": "पैक किया गया",

    // Categories
    "category.vegetables": "सब्जियां",
    "category.fruits": "फल",
    "category.grains": "अनाज",
    "category.spices": "मसाले",
    "category.oil": "तेल",
    "category.dairy": "डेयरी",
    "category.meat": "मांस",
    "category.fish": "मछली",

    // Time
    "time.today": "आज",
    "time.yesterday": "कल",
    "time.this_week": "इस सप्ताह",
    "time.this_month": "इस महीने",
    "time.days_ago": "दिन पहले",
    "time.hours_ago": "घंटे पहले",
    "time.minutes_ago": "मिनट पहले",

    // Language
    "language.hindi": "हिंदी",
    "language.english": "English",
    "language.select": "भाषा चुनें",

    // Additional translations for missing keys
    "stats.last_month": "पिछले महीने से",
    "stats.this_month": "इस महीने",
    "stats.verified": "सत्यापित",
    "stats.from_suppliers": "आपूर्तिकर्ताओं से",
    "stats.items_low": "आइटम्स कम हैं",
    "stats.recent_orders_desc": "आपके पिछले ऑर्डर्स की स्थिति",
    "stats.top_suppliers_desc": "आपके पसंदीदा और विश्वसनीय सप्लायर्स",
    "stats.quick_actions_desc": "अपने व्यापार को तेज़ी से आगे बढ़ाएं",
    "stats.orders": "ऑर्डर्स",
    "stats.savings": "बचत",
    "reviews.text": "रिव्यू",
    "location.karol_bagh": "करोल बाग, दिल्ली",
    "location.chandni_chowk": "चांदनी चौक, दिल्ली",
    "location.lajpat_nagar": "लाजपत नगर, दिल्ली",
    "location.connaught_place": "कनॉट प्लेस, दिल्ली",
    "location.jama_masjid": "जामा मस्जिद, दिल्ली",
    "location.gurgaon": "गुड़गांव, हरियाणा",
    "discount.text": "छूट",
    "delivery.hours": "घंटे",
    "items.onion": "प्याज",
    "items.tomato": "टमाटर",
    "items.green_chili": "हरी मिर्च",
    "items.garam_masala": "गरम मसाला",
    "items.coriander_powder": "धनिया पाउडर",
    "items.turmeric_powder": "हल्दी पाउडर",
    "items.basmati_rice": "बासमती चावल",
    "items.toor_dal": "तूर दाल",
    "items.mustard_oil": "सरसों का तेल",
    "items.ghee": "घी",
    "items.paneer": "पनीर",
    "items.curd": "दही",
    "payment.upi_placeholder": "yourname@paytm या 9876543210",
    "payment.card_number": "कार्ड नंबर",
    "payment.card_holder": "कार्डधारक का नाम",
    "payment.expiry_date": "एक्सपायरी डेट",
    "payment.select_wallet": "वॉलेट चुनें",
    "payment.cod_description": "डिलीवरी के समय नकद भुगतान करें। कृपया सही पैसे तैयार रखें।",
    "payment.prepare_cash": "सही पैसे तैयार रखें",
    "user.name": "राजेश कुमार",
    "user.initials": "RK",
    "company.name": "VendorConnect",
    "company.tagline": "स्ट्रीट फूड वेंडर्स के लिए विश्वसनीय आपूर्ति श्रृंखला",
    // Bulk Orders - Additional keys
    "bulk_orders.subtitle": "अन्य वेंडर्स के साथ मिलकर बेहतर दाम पाएं",
    "bulk_orders.create_new": "नया बल्क ऑर्डर बनाएं",
    "bulk_orders.create_description": "अन्य वेंडर्स के साथ मिलकर बल्क में ऑर्डर करें और पैसे बचाएं",
    "bulk_orders.product_name": "प्रोडक्ट का नाम",
    "bulk_orders.product_placeholder": "जैसे: प्याज, चावल, मसाले",
    "bulk_orders.category": "श्रेणी",
    "bulk_orders.select_category": "श्रेणी चुनें",
    "bulk_orders.target_quantity": "टारगेट मात्रा",
    "bulk_orders.quantity_placeholder": "जैसे: 500 किलो",
    "bulk_orders.deadline": "डेडलाइन",
    "bulk_orders.description": "विवरण",
    "bulk_orders.description_placeholder": "प्रोडक्ट की गुणवत्ता और अन्य जरूरी जानकारी",
    "bulk_orders.create_order": "बल्क ऑर्डर बनाएं",
    "bulk_orders.how_it_works": "बल्क ऑर्डर कैसे काम करता है?",
    "bulk_orders.step1_title": "ऑर्डर बनाएं या जुड़ें",
    "bulk_orders.step1_desc": "नया बल्क ऑर्डर बनाएं या मौजूदा ऑर्डर में शामिल हों",
    "bulk_orders.step2_title": "टारगेट पूरा करें",
    "bulk_orders.step2_desc": "जब टारगेट मात्रा पूरी हो जाए, ऑर्डर कन्फर्म हो जाता है",
    "bulk_orders.step3_title": "बचत पाएं",
    "bulk_orders.step3_desc": "बल्क रेट पर सामान मिलता है और सभी को फायदा होता है",
    "bulk_orders.active_orders": "एक्टिव बल्क ऑर्डर्स",
    "bulk_orders.progress": "प्रगति",
    "bulk_orders.savings": "बचत",
    "bulk_orders.bulk_price": "बल्क प्राइस",
    "bulk_orders.market_price": "मार्केट प्राइस",
    "bulk_orders.members": "सदस्य",
    "bulk_orders.join_order": "इस ऑर्डर में शामिल हों",
    "bulk_orders.view_details": "विवरण देखें",
    "bulk_orders.completed_orders": "पूरे हो चुके ऑर्डर्स",
    "bulk_orders.no_active_orders": "कोई एक्टिव बल्क ऑर्डर नहीं",
    "bulk_orders.empty_state_desc": "नया बल्क ऑर्डर बनाएं या मौजूदा ऑर्डर में शामिल हों",
    "bulk_orders.create_first_order": "पहला बल्क ऑर्डर बनाएं",

    // Categories - Additional keys
    "categories.vegetables": "सब्जियां",
    "categories.grains": "अनाज",
    "categories.spices": "मसाले",
    "categories.oil": "तेल",
    "categories.dairy": "डेयरी",
  },
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.suppliers": "Suppliers",
    "nav.orders": "Orders",
    "nav.bulk_orders": "Bulk Orders",
    "nav.inventory": "Inventory",
    "nav.tracking": "Tracking",
    "nav.payments": "Payments",
    "nav.admin": "Admin",
    "nav.help": "Help",
    "nav.login": "Login",
    "nav.logout": "Logout",

    // Landing Page
    "landing.title": "Empower India's",
    "landing.subtitle": "Street Food Vendors",
    "landing.description":
      "Connect with reliable suppliers, get better prices, and grow your business. Trusted by thousands of vendors.",
    "landing.get_started": "Get Started",
    "landing.watch_demo": "Watch Demo",
    "landing.problems_solutions": "Problems & Solutions",
    "landing.current_challenges": "Current Challenges",
    "landing.with_vendorconnect": "With VendorConnect",
    "landing.key_features": "Key Features",
    "landing.verified_suppliers": "Verified Suppliers",
    "landing.better_prices": "Better Prices",
    "landing.local_network": "Local Network",
    "landing.how_it_works": "How It Works",
    "landing.register": "Register",
    "landing.find_suppliers": "Find Suppliers",
    "landing.place_order": "Place Order",
    "landing.success_stories": "Success Stories",
    "landing.start_today": "Start Today",
    "landing.start_free": "Start Free",

    // Problem statements
    "landing.problem1": "Unreliable suppliers and quality issues",
    "landing.problem2": "High costs and hidden charges",
    "landing.problem3": "No access to wholesale rates",
    "landing.problem4": "Lack of transparent pricing",

    // Solutions
    "landing.solution1": "Verified and reliable suppliers",
    "landing.solution2": "Transparent pricing",
    "landing.solution3": "Better prices through collective buying",
    "landing.solution4": "Instant connection with local suppliers",

    // Feature descriptions
    "landing.verified_desc": "All suppliers go through complete verification process. Quality guaranteed.",
    "landing.better_prices_desc": "Save 15-30% through collective buying and competitive pricing.",
    "landing.local_network_desc": "Connect with local suppliers in your area. Fast delivery and lower costs.",

    // How it works steps
    "landing.step1_desc": "Create your account and tell us your requirements",
    "landing.step2_desc": "Browse verified suppliers in your area",
    "landing.step3_desc": "Order at better prices and get fast delivery",

    // Success stories
    "landing.vendor1_name": "Rajesh Kumar",
    "landing.vendor1_role": "Chat Vendor, Delhi",
    "landing.vendor1_quote":
      "VendorConnect reduced my costs by 25%. Now I get quality ingredients and my customers are happy too.",
    "landing.vendor2_name": "Priya Sharma",
    "landing.vendor2_role": "Dosa Stall, Bangalore",
    "landing.vendor2_quote": "Earlier I had to go to different places. Now I get everything from one platform.",

    // CTA section
    "landing.cta_desc": "Thousands of vendors are already using VendorConnect. Join them!",

    // Footer
    "footer.tagline": "Empowering India's Street Food Vendors",
    "footer.help_center": "Help Center",
    "footer.contact": "Contact Us",
    "footer.faq": "FAQ",
    "footer.about": "About Us",
    "footer.careers": "Careers",
    "footer.privacy": "Privacy Policy",
    "footer.rights": "All rights reserved.",
    "footer.company": "Company",

    // Login Page
    "login.welcome": "Welcome! 👋",
    "login.description": "Login to grow your business",
    "login.account_description": "Login to your account",
    "login.phone_number": "Phone Number",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.password_placeholder": "Enter your password",
    "login.phone_placeholder": "9876543210",
    "login.email_placeholder": "your@email.com",
    "login.remember_me": "Remember me",
    "login.forgot_password": "Forgot password?",
    "login.login_button": "Login",
    "login.login_with_otp": "Login with OTP",
    "login.login_with_google": "Login with Google",
    "login.or": "or",
    "login.no_account": "Don't have an account?",
    "login.register": "Register",
    "login.phone_tab": "Phone Number",
    "login.email_tab": "Email",

    // Dashboard
    "dashboard.welcome": "Hello Rajesh! 👋",
    "dashboard.welcome_desc": "View your business status and place new orders",
    "dashboard.monthly_savings": "Monthly Savings",
    "dashboard.total_orders": "Total Orders",
    "dashboard.active_suppliers": "Active Suppliers",
    "dashboard.average_rating": "Average Rating",
    "dashboard.low_stock_alert": "Low Stock Alert",
    "dashboard.recent_orders": "Recent Orders",
    "dashboard.top_suppliers": "Top Suppliers",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.find_suppliers": "Find New Suppliers",
    "dashboard.bulk_order": "Place Bulk Order",
    "dashboard.market_prices": "View Market Prices",
    "dashboard.price_alerts": "Set Price Alerts",
    "dashboard.manage_inventory": "Manage Inventory",

    // Suppliers Page
    "suppliers.title": "Suppliers",
    "suppliers.description": "Find verified and reliable suppliers",
    "suppliers.search_placeholder": "Search suppliers or products...",
    "suppliers.select_category": "Select Category",
    "suppliers.select_location": "Select Location",
    "suppliers.all_categories": "All Categories",
    "suppliers.all_locations": "All Locations",
    "suppliers.more_filters": "More Filters",
    "suppliers.results_found": "suppliers found",
    "suppliers.sort_by_rating": "Sort by Rating",
    "suppliers.sort_by_distance": "Sort by Distance",
    "suppliers.sort_by_price": "Sort by Price",
    "suppliers.sort_by_delivery": "Sort by Delivery Time",
    "suppliers.min_order": "Min Order:",
    "suppliers.specialties": "Specialties:",
    "suppliers.order_now": "Order Now",
    "suppliers.view_details": "View Details",
    "suppliers.load_more": "Load More Suppliers",
    "suppliers.no_results": "No suppliers found",
    "suppliers.no_results_desc": "Try changing your search criteria",
    "suppliers.clear_filters": "Clear Filters",

    // Orders Page
    "orders.title": "My Orders",
    "orders.description": "View information about all your orders",
    "orders.download_report": "Download Report",
    "orders.search_placeholder": "Search order ID or supplier...",
    "orders.status_filter": "Status Filter",
    "orders.time_filter": "Time Filter",
    "orders.all_status": "All Status",
    "orders.all_time": "All Time",
    "orders.today": "Today",
    "orders.this_week": "This Week",
    "orders.this_month": "This Month",
    "orders.this_quarter": "This Quarter",
    "orders.order_history": "Order History",
    "orders.order_id": "Order ID",
    "orders.supplier": "Supplier",
    "orders.items": "Items",
    "orders.amount": "Amount",
    "orders.status": "Status",
    "orders.order_date": "Order Date",
    "orders.action": "Action",
    "orders.more_items": "more items",
    "orders.pending_orders": "Pending Orders",
    "orders.processing_transit": "Processing + Transit",
    "orders.total_spent": "Total Spent",
    "orders.average_order": "Average Order",
    "orders.per_order": "per order",
    "orders.orders_found": "orders found",
    "orders.no_orders_found": "No orders found",
    "orders.try_changing_filters": "Try changing your filters",

    // Bulk Orders
    "bulk.title": "Bulk Orders",
    "bulk.description": "Get better prices by joining with other vendors",
    "bulk.create_new": "Create New Bulk Order",
    "bulk.how_it_works": "How Bulk Orders Work?",
    "bulk.step1": "Create or Join Order",
    "bulk.step1_desc": "Create a new bulk order or join an existing one",
    "bulk.step2": "Reach Target",
    "bulk.step2_desc": "When target quantity is reached, order gets confirmed",
    "bulk.step3": "Get Savings",
    "bulk.step3_desc": "Get bulk rates and everyone benefits",
    "bulk.active_orders": "Active Bulk Orders",
    "bulk.completed_orders": "Completed Orders",
    "bulk.progress": "Progress:",
    "bulk.savings": "savings",
    "bulk.bulk_price": "Bulk Price",
    "bulk.market_price": "Market Price",
    "bulk.members": "members",
    "bulk.deadline": "remaining",
    "bulk.join_order": "Join This Order",
    "bulk.create_first": "Create First Bulk Order",
    // Bulk Orders - Additional keys
    "bulk_orders.subtitle": "Get better prices by joining with other vendors",
    "bulk_orders.create_new": "Create New Bulk Order",
    "bulk_orders.create_description": "Join with other vendors to order in bulk and save money",
    "bulk_orders.product_name": "Product Name",
    "bulk_orders.product_placeholder": "e.g: Onion, Rice, Spices",
    "bulk_orders.category": "Category",
    "bulk_orders.select_category": "Select Category",
    "bulk_orders.target_quantity": "Target Quantity",
    "bulk_orders.quantity_placeholder": "e.g: 500 kg",
    "bulk_orders.deadline": "Deadline",
    "bulk_orders.description": "Description",
    "bulk_orders.description_placeholder": "Product quality and other important information",
    "bulk_orders.create_order": "Create Bulk Order",
    "bulk_orders.how_it_works": "How Bulk Orders Work?",
    "bulk_orders.step1_title": "Create or Join Order",
    "bulk_orders.step1_desc": "Create a new bulk order or join an existing one",
    "bulk_orders.step2_title": "Reach Target",
    "bulk_orders.step2_desc": "When target quantity is reached, order gets confirmed",
    "bulk_orders.step3_title": "Get Savings",
    "bulk_orders.step3_desc": "Get bulk rates and everyone benefits",
    "bulk_orders.active_orders": "Active Bulk Orders",
    "bulk_orders.progress": "Progress",
    "bulk_orders.savings": "savings",
    "bulk_orders.bulk_price": "Bulk Price",
    "bulk_orders.market_price": "Market Price",
    "bulk_orders.members": "members",
    "bulk_orders.join_order": "Join This Order",
    "bulk_orders.view_details": "View Details",
    "bulk_orders.completed_orders": "Completed Orders",
    "bulk_orders.no_active_orders": "No Active Bulk Orders",
    "bulk_orders.empty_state_desc": "Create a new bulk order or join an existing one",
    "bulk_orders.create_first_order": "Create First Bulk Order",

    // Categories - Additional keys
    "categories.vegetables": "Vegetables",
    "categories.grains": "Grains",
    "categories.spices": "Spices",
    "categories.oil": "Oil",
    "categories.dairy": "Dairy",

    // Inventory
    "inventory.title": "Inventory Management",
    "inventory.description": "Track and manage your stock",
    "inventory.add_item": "Add New Item",
    "inventory.total_items": "Total Items",
    "inventory.low_stock": "Low Stock Alert",
    "inventory.stock_value": "Total Stock Value",
    "inventory.turnover": "Average Turnover",
    "inventory.in_stock": "In Stock",
    "inventory.out_of_stock": "Out of Stock",
    "inventory.reorder_now": "Reorder Now",
    "inventory.search_placeholder": "Search items...",
    "inventory.category_filter": "Category Filter",
    "inventory.status_filter": "Status Filter",
    "inventory.item": "Item",
    "inventory.category": "Category",
    "inventory.current_stock": "Current Stock",
    "inventory.stock_level": "Stock Level",
    "inventory.cost": "Cost",
    "inventory.avg_consumption": "Avg Consumption",

    // Payments
    "payments.title": "Payments",
    "payments.description": "Secure and easy payment options",
    "payments.choose_method": "Choose Payment Method",
    "payments.upi": "UPI",
    "payments.wallet": "Digital Wallet",
    "payments.card": "Debit/Credit Card",
    "payments.cod": "Cash on Delivery",
    "payments.order_summary": "Order Summary",
    "payments.subtotal": "Subtotal",
    "payments.delivery_charge": "Delivery Charge",
    "payments.processing_fee": "Processing Fee",
    "payments.total_amount": "Total Amount",
    "payments.pay_now": "Pay",
    "payments.secure_payment": "🔒 Your payment is secured with 256-bit SSL encryption",
    "payments.recent_transactions": "Recent Transactions",
    "payments.free": "Free",
    "payments.popular": "Popular",

    // Tracking
    "tracking.title": "Order Tracking",
    "tracking.description": "View live status of your order",
    "tracking.live_location": "Live Location",
    "tracking.order_status": "Order Status",
    "tracking.estimated_delivery": "Estimated Delivery",
    "tracking.contact_info": "Contact Information",
    "tracking.supplier": "Supplier",
    "tracking.delivery_partner": "Delivery Partner",
    "tracking.need_help": "Need Help?",
    "tracking.chat_support": "Chat Support",
    "tracking.helpline": "1800-123-4567",
    "tracking.track_order": "Track Order",
    "tracking.tracking_id_placeholder": "Enter tracking ID (e.g., TRK001235)",
    "tracking.distance_remaining": "Distance Remaining",
    "tracking.expected_time": "Expected Time",
    "tracking.call_delivery": "Call Delivery Partner",
    "tracking.message": "Message",
    "tracking.order_progress": "Order Progress",
    "tracking.order_confirmed": "Order Confirmed",
    "tracking.packing": "Packing",
    "tracking.in_transit": "In Transit",
    "tracking.delivered": "Delivered",
    "tracking.delivery_address": "Delivery Address",
    "tracking.order_summary": "Order Details",
    "tracking.tracking_id": "Tracking ID",

    // Common
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.submit": "Submit",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view_all": "View All",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.pending": "Pending",
    "common.completed": "Completed",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.close": "Close",
    "common.open": "Open",
    "common.yes": "Yes",
    "common.no": "No",

    // Status
    "status.delivered": "Delivered",
    "status.in_transit": "In Transit",
    "status.processing": "Processing",
    "status.cancelled": "Cancelled",
    "status.confirmed": "Confirmed",
    "status.packed": "Packed",

    // Categories
    "category.vegetables": "Vegetables",
    "category.fruits": "Fruits",
    "category.grains": "Grains",
    "category.spices": "Spices",
    "category.oil": "Oil",
    "category.dairy": "Dairy",
    "category.meat": "Meat",
    "category.fish": "Fish",

    // Time
    "time.today": "Today",
    "time.yesterday": "Yesterday",
    "time.this_week": "This Week",
    "time.this_month": "This Month",
    "time.days_ago": "days ago",
    "time.hours_ago": "hours ago",
    "time.minutes_ago": "minutes ago",

    // Language
    "language.hindi": "हिंदी",
    "language.english": "English",
    "language.select": "Select Language",

    // Additional translations for missing keys
    "stats.last_month": "from last month",
    "stats.this_month": "this month",
    "stats.verified": "verified",
    "stats.from_suppliers": "from suppliers",
    "stats.items_low": "items are low",
    "stats.recent_orders_desc": "Status of your recent orders",
    "stats.top_suppliers_desc": "Your favorite and reliable suppliers",
    "stats.quick_actions_desc": "Quickly grow your business",
    "stats.orders": "orders",
    "stats.savings": "savings",
    "reviews.text": "reviews",
    "location.karol_bagh": "Karol Bagh, Delhi",
    "location.chandni_chowk": "Chandni Chowk, Delhi",
    "location.lajpat_nagar": "Lajpat Nagar, Delhi",
    "location.connaught_place": "Connaught Place, Delhi",
    "location.jama_masjid": "Jama Masjid, Delhi",
    "location.gurgaon": "Gurgaon, Haryana",
    "discount.text": "discount",
    "delivery.hours": "hours",
    "items.onion": "Onion",
    "items.tomato": "Tomato",
    "items.green_chili": "Green Chili",
    "items.garam_masala": "Garam Masala",
    "items.coriander_powder": "Coriander Powder",
    "items.turmeric_powder": "Turmeric Powder",
    "items.basmati_rice": "Basmati Rice",
    "items.toor_dal": "Toor Dal",
    "items.mustard_oil": "Mustard Oil",
    "items.ghee": "Ghee",
    "items.paneer": "Paneer",
    "items.curd": "Curd",
    "payment.upi_placeholder": "yourname@paytm or 9876543210",
    "payment.card_number": "Card Number",
    "payment.card_holder": "Cardholder Name",
    "payment.expiry_date": "Expiry Date",
    "payment.select_wallet": "Select Wallet",
    "payment.cod_description": "Pay cash on delivery. Please keep exact change ready.",
    "payment.prepare_cash": "keep exact change ready",
    "user.name": "Rajesh Kumar",
    "user.initials": "RK",
    "company.name": "VendorConnect",
    "company.tagline": "Reliable Supply Chain for Street Food Vendors",
    // Bulk Orders - Additional keys
    "bulk_orders.subtitle": "Get better prices by joining with other vendors",
    "bulk_orders.create_new": "Create New Bulk Order",
    "bulk_orders.create_description": "Join with other vendors to order in bulk and save money",
    "bulk_orders.product_name": "Product Name",
    "bulk_orders.product_placeholder": "e.g: Onion, Rice, Spices",
    "bulk_orders.category": "Category",
    "bulk_orders.select_category": "Select Category",
    "bulk_orders.target_quantity": "Target Quantity",
    "bulk_orders.quantity_placeholder": "e.g: 500 kg",
    "bulk_orders.deadline": "Deadline",
    "bulk_orders.description": "Description",
    "bulk_orders.description_placeholder": "Product quality and other important information",
    "bulk_orders.create_order": "Create Bulk Order",
    "bulk_orders.how_it_works": "How Bulk Orders Work?",
    "bulk_orders.step1_title": "Create or Join Order",
    "bulk_orders.step1_desc": "Create a new bulk order or join an existing one",
    "bulk_orders.step2_title": "Reach Target",
    "bulk_orders.step2_desc": "When target quantity is reached, order gets confirmed",
    "bulk_orders.step3_title": "Get Savings",
    "bulk_orders.step3_desc": "Get bulk rates and everyone benefits",
    "bulk_orders.active_orders": "Active Bulk Orders",
    "bulk_orders.progress": "Progress",
    "bulk_orders.savings": "savings",
    "bulk_orders.bulk_price": "Bulk Price",
    "bulk_orders.market_price": "Market Price",
    "bulk_orders.members": "members",
    "bulk_orders.join_order": "Join This Order",
    "bulk_orders.view_details": "View Details",
    "bulk_orders.completed_orders": "Completed Orders",
    "bulk_orders.no_active_orders": "No Active Bulk Orders",
    "bulk_orders.empty_state_desc": "Create a new bulk order or join an existing one",
    "bulk_orders.create_first_order": "Create First Bulk Order",

    // Categories - Additional keys
    "categories.vegetables": "Vegetables",
    "categories.grains": "Grains",
    "categories.spices": "Spices",
    "categories.oil": "Oil",
    "categories.dairy": "Dairy",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("vendorconnect-language") as Language
    if (savedLanguage && (savedLanguage === "hi" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    } else {
      setLanguage("en") // Default to English
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("vendorconnect-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
